name: DEPLOY
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  stop:
    name: podman
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Stop Container
        run: |
          podman stop dict-api-deployed

  deploy:
    name: Create Container
    runs-on: self-hosted
    continue-on-error: false
    steps:
      - name: Get source
        uses: actions/checkout@main
      - name: Create container and run tests
        run: |
          podman-compose up