name: DEPLOY
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  stop:
    name: podman
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Stop Container
        run: |
          systemctl stop container-dict-api-deployed

  deploy:
    name: Create Container
    runs-on: self-hosted
    continue-on-error: false
    steps:
      - name: Get source
        uses: actions/checkout@main
      - name: Create container and run tests
        run: |
          podman build . -t whosthegoss/dict-api:latest
          podman push whosthegoss/dict-api:latest

  start:
    name: podman
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Start Container
        run: |
          systemctl start container-dict-api-deployed