name: DEPLOY
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  deploy:
    name: podman
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Stop Pod
        run: |
          podman stop run-dict-api
      - name: Get source
        uses: actions/checkout@main
      - name: Create container and run tests
        run: |
          podman build -t dict-api -tag latest .
      - name: Run that container
        run: |
          podman  run -dt --rm -p 8888:3000 --name run-dict-api dict-api